export type PineconeMetadata = {
  tenantId: string;
  entityType: "tenant_profile" | "product" | "product_variant";
  entityId: string;
  chunkType?: string;
  chunkKey?: string;
  chunkIndex?: number;
  subdomain?: string;
  shopName?: string;
  shopType?: string;
  productCategory?: string;
  productId?: string;
  variantId?: string;
  variantSize?: string;
  variantColor?: string;
  isActive: boolean;
  relationTenantNode: string;
  relationNode: string;
  text: string;
};
